In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Task 1 -Create Project DataFrame

project = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
})

project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [ ]:
# Task 2 - Create Employee DataFrame

employee = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
})

employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [ ]:
# Task - 3 Create Seniority Level DataFrame

seniority = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
})

seniority

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [5]:
# Save DataFrames as CSV files

project.to_csv("project.csv", index=False)
employee.to_csv("employee.csv", index=False)
seniority.to_csv("seniority.csv", index=False)

print("All CSV files saved successfully!")

All CSV files saved successfully!

In [6]:
# Fill missing Cost values using running average

cost_list = project["Cost"].tolist()

for i in range(len(cost_list)):
    if pd.isna(cost_list[i]):
        cost_list[i] = sum(cost_list[:i]) / len(cost_list[:i])

project["Cost"] = cost_list

project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [7]:
# Split Name into First Name and Last Name

employee[["First Name", "Last Name"]] = employee["Name"].str.split(" ", n=1, expand=True)

employee.drop("Name", axis=1, inplace=True)

employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [ ]:
# Task - 4 Join all three DataFrames

Final = pd.merge(project, employee, on="ID")
Final = pd.merge(Final, seniority, on="ID")

Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3

In [9]:
# Task 5 - Add Bonus Column

Final["Bonus"] = 0

Final.loc[Final["Status"] == "Finished", "Bonus"] = Final["Cost"] * 0.05

Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000

In [ ]:
# Task 6 - Demote Failed Employees and Remove level Above 4

Final.loc[Final["Status"] == "Failed", "Designation Level"] = Final.loc[
    Final["Status"] == "Failed", "Designation Level"
] - 1

Final = Final[Final["Designation Level"] <= 4]

Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,1,0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,2,0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,1,0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000

In [ ]:
# Task 7 - Add Mr./Mrs. and drop gender coloumn

Final.loc[Final["Gender"] == "M", "First Name"] = "Mr. " + Final["First Name"]
Final.loc[Final["Gender"] == "F", "First Name"] = "Mrs. " + Final["First Name"]

Final.drop("Gender", axis=1, inplace=True)

Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,20000
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,2,0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,1,0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,10000

In [ ]:
# Task 8 - promote employees above age 29

for i in range(len(Final)):
    if Final.loc[i, "Age"] > 29:
        Final.loc[i, "Designation Level"] = Final.loc[i, "Designation Level"] + 1

Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,4,162525
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,4,20000
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,2,0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,1,0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,4,10000

In [13]:
# Task 9 - Create TotalProjCost DataFrame

TotalProjCost = Final.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

TotalProjCost.rename(columns={"Cost": "Total Cost"}, inplace=True)

TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

In [ ]:
# Task 10 - Display Employees whose city contains 'o'

Final[Final["City"].str.contains("o", case=False)]

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000